### ISSUE TITLE
rizzy -n doesn't handle large negative value

### ISSUE THREAD

**Issue by jordansamuels** [aquanauts/rizzy#2]
```
% echo '-9223372036854775808' | rizzy -n
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: PosOverflow }', src/rizzy.rs:77:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
% echo '-9223372036854775807' | rizzy -n
-2262-04-11T17:47:16.854775807-06:00
% rizzy --version
rizzy 0.1.1
```

**Comment by siedentop** [comment]
@jordansamuels what is the expected behavior you'd like to see? 

Is your second run, with the date being "negative" is that what you'd expect?

For the crash in the first example, it would be a breeze to get a cleaner error/exit. But I just would like to know if could think of better behavior that should occur.

EDIT: An alternative would be to simply keep any log line that would otherwise have failed rizzy untouched. What do you think?
